# 异常处理

`_7_try_catch`

```c
@try {
    NSLog(@"%@",[array objectAtIndex:0]);
}
@catch (NSException *exception) {
    // catch: NSRangeException,*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
    NSLog(@"catch: %@,%@",[exception name],[exception reason]);
}
@finally {
    NSLog(@"finally");
}
```

`@throw`：抛出异常。

在错误发生之前做测试，而不是错误发生后捕获它。测试方法的错误并返回一些值作为错误的标识，而不是抛出异常。抛出异常通常会使用大量的系统资源，反对非必要的使用异常。